### ISSUE TITLE
steganography encoding and decoding not working

### ISSUE THREAD

**Issue by FreddieMG** [pawel-kaczmarek/The-A-Files#1]
Hey,
I tried to encode and decode a small binary array in a short audio of 9 seconds and for some reason the original message did not match the encoded result nor the length of it.

I attempted  using DsssMethod and PatchworkMultilayerMethod and got the same results on both.

Are some general limitations I might be missing for the input or usage?

**Comment by pawel-kaczmarek** [comment]
Hello,

Can you send both the message and the audio signal in which you hide the message?

Methods have their assumptions and limitations. You need to read the articles and documentation describing them (README).
